import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { roboto } from "@/styles/fonts";
import { Toaster } from "sonner";
import Header from "@/components/global/Header";
import Navbar from "@/components/global/Navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          roboto.className,
          'antialiased min-h-screen w-full flex flex-col relative bg-background text-foreground overflow-x-hidden'
        )}
      >
        <Toaster position="top-center" />
        <Header />
        <div className="flex-1 w-full max-w-screen-2xl mx-auto">
          {children}
        </div>
        <Navbar />
      </body>
    </html>
  );
}
