import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { roboto } from "@/styles/fonts";
import Navbar from "@/components/global/Navbar";
import Header from "@/components/global/Header";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body
        className={ cn(roboto.className, 'antialiased min-h-screen w-sm')}
      >
      <Toaster />
      <Header />
        {children}
      <Navbar />

      </body>
    </html>
  );
}
